In [12]:
import pandas as pd 
data = {
"names":[
"Rahim Uddin", "Karina Khan", "John Smith", "Mei Lin", "Alex Brown",
"Sara Ahmed", "David Lee","Thomas Alva", "Maria Garcia","Devid Ton", "Chen Wei", "Fatima Noor"
],

"cities":[
"Dhaka", "Karachi", "London", "Beijing","UK London", "New York",
"Cairo", "Seoul","London", "Madrid", "Shanghai", "Dubai"
],

"departments":[
"IT", "HR", "Finance", "Marketing", "IT","Finance",
"Sales", "IT", "HR","IT", "Finance", "Marketing"
],

"salaries":[
    55000, 48000, 72000,59000, 60000, 80000,50000,69000, 67000, 53000, 75000, 62000
]}
df = pd.DataFrame(data)
print(df)

           names     cities departments  salaries
0    Rahim Uddin      Dhaka          IT     55000
1    Karina Khan    Karachi          HR     48000
2     John Smith     London     Finance     72000
3        Mei Lin    Beijing   Marketing     59000
4     Alex Brown  UK London          IT     60000
5     Sara Ahmed   New York     Finance     80000
6      David Lee      Cairo       Sales     50000
7    Thomas Alva      Seoul          IT     69000
8   Maria Garcia     London          HR     67000
9      Devid Ton     Madrid          IT     53000
10      Chen Wei   Shanghai     Finance     75000
11   Fatima Noor      Dubai   Marketing     62000

## Filtering based on String

In [3]:
# str contains 
df.loc[df['departments'].str.contains('HR')]

          names   cities departments  salaries
1   Karina Khan  Karachi          HR     48000
7  Maria Garcia   Madrid          HR     53000

In [8]:
# case different  
df.loc[df['departments'].str.contains('hr',case = False)]

         names   cities departments  salaries
1  Karina Khan  Karachi          HR     48000
7  Thomas Alva   London          HR     67000

In [7]:
df.loc[df['departments'].str.contains('IT')]

          names    cities departments  salaries
0   Rahim Uddin     Dhaka          IT     55000
4    Alex Brown  New York          IT     80000
6     David Lee     Seoul          IT     69000
8  Maria Garcia    Madrid          IT     53000

In [13]:
# starts with lon

df.loc[df['cities'].str.contains(r'lon',case = False)]

          names     cities departments  salaries
2    John Smith     London     Finance     72000
4    Alex Brown  UK London          IT     60000
8  Maria Garcia     London          HR     67000

In [14]:
# starts with New

df.loc[df['cities'].str.contains(r'new',case = False)]

        names    cities departments  salaries
5  Sara Ahmed  New York     Finance     80000

In [16]:
 # start with  first word in lon  
df.loc[df['cities'].str.contains(r'^lon',case = False)]

          names  cities departments  salaries
2    John Smith  London     Finance     72000
8  Maria Garcia  London          HR     67000

In [18]:
 # end with  last word in on  
df.loc[df['cities'].str.contains(r'on$',case = False)]

          names     cities departments  salaries
2    John Smith     London     Finance     72000
4    Alex Brown  UK London          IT     60000
8  Maria Garcia     London          HR     67000

In [20]:
# name starts with a vowel 
df.loc[df['names'].str.contains(r"^[aeiou]",case =  False)]

        names     cities departments  salaries
4  Alex Brown  UK London          IT     60000

In [24]:
#multiple 
df.loc[df["cities"].str.contains(r"new|lon",case = False)]

          names     cities departments  salaries
2    John Smith     London     Finance     72000
4    Alex Brown  UK London          IT     60000
5    Sara Ahmed   New York     Finance     80000
8  Maria Garcia     London          HR     67000

In [29]:
#multiple 
df.loc[
    df["cities"].str.contains(r"new|lon",case = False) & 
    df['names'].str.contains(r"^[aeiou]",case = False)
    ]

        names     cities departments  salaries
4  Alex Brown  UK London          IT     60000

In [28]:
#multiple 
df.loc[
    df["cities"].str.contains(r"new|lon",case = False) |
    df['names'].str.contains(r"^[aeiou]",case = False)
    ]

          names     cities departments  salaries
2    John Smith     London     Finance     72000
4    Alex Brown  UK London          IT     60000
5    Sara Ahmed   New York     Finance     80000
8  Maria Garcia     London          HR     67000

## Adding new column and saving  the file

In [30]:
import pandas as pd 
df = pd.read_csv('student_data.csv')
df

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
13    PH1014        Urmi Akter  ...   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
18    PH1019      Faria Rahman  ...   Mr. David  Chattogram
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[20 rows x 9 columns]

In [32]:
# adding a column with constant value
df['Country'] = 'Bangladesh'
df

   StudentID          FullName  ...    Location     Country
0     PH1001       Alif Rahman  ...       Dhaka  Bangladesh
1     PH1002     Fatima Akhter  ...  Chattogram  Bangladesh
2     PH1003     Imran Hossain  ...       Dhaka  Bangladesh
3     PH1004  Jannatul Ferdous  ...      Sylhet  Bangladesh
4     PH1005       Kamal Uddin  ...  Chattogram  Bangladesh
5     PH1006       Laila Begum  ...    Rajshahi  Bangladesh
6     PH1007    Mahmudul Hasan  ...       Dhaka  Bangladesh
7     PH1008       Nadia Islam  ...  Chattogram  Bangladesh
8     PH1009        Omar Faruq  ...       Dhaka  Bangladesh
9     PH1010      Priya Sharma  ...      Sylhet  Bangladesh
10    PH1011      Rahim Sheikh  ...      Khulna  Bangladesh
11    PH1012   Sadia Chowdhury  ...  Chattogram  Bangladesh
12    PH1013      Tanvir Ahmed  ...       Dhaka  Bangladesh
13    PH1014        Urmi Akter  ...    Rajshahi  Bangladesh
14    PH1015      Wahiduzzaman  ...       Dhaka  Bangladesh
15    PH1016      Ziaur Rahman  ...  Chattogram  Bangladesh
16    PH1017       Afsana Mimi  ...       Dhaka  Bangladesh
17    PH1018       Babul Ahmed  ...      Sylhet  Bangladesh
18    PH1019      Faria Rahman  ...  Chattogram  Bangladesh
19    PH1020        Nasir Khan  ...       Dhaka  Bangladesh

[20 rows x 10 columns]

In [33]:
# cerate a new column Total marks, that contains all mark summation
df['Total Marks'] = df['Data Structure Marks']+ df['Algorithm Marks']+df['Python Marks']
df

   StudentID          FullName  ...     Country  Total Marks
0     PH1001       Alif Rahman  ...  Bangladesh        258.0
1     PH1002     Fatima Akhter  ...  Bangladesh          NaN
2     PH1003     Imran Hossain  ...  Bangladesh        261.0
3     PH1004  Jannatul Ferdous  ...  Bangladesh        238.0
4     PH1005       Kamal Uddin  ...  Bangladesh          NaN
5     PH1006       Laila Begum  ...  Bangladesh        228.0
6     PH1007    Mahmudul Hasan  ...  Bangladesh          NaN
7     PH1008       Nadia Islam  ...  Bangladesh        247.0
8     PH1009        Omar Faruq  ...  Bangladesh        220.0
9     PH1010      Priya Sharma  ...  Bangladesh        266.0
10    PH1011      Rahim Sheikh  ...  Bangladesh          NaN
11    PH1012   Sadia Chowdhury  ...  Bangladesh        257.0
12    PH1013      Tanvir Ahmed  ...  Bangladesh        229.0
13    PH1014        Urmi Akter  ...  Bangladesh          NaN
14    PH1015      Wahiduzzaman  ...  Bangladesh        256.0
15    PH1016      Ziaur Rahman  ...  Bangladesh          NaN
16    PH1017       Afsana Mimi  ...  Bangladesh        273.0
17    PH1018       Babul Ahmed  ...  Bangladesh        261.0
18    PH1019      Faria Rahman  ...  Bangladesh          NaN
19    PH1020        Nasir Khan  ...  Bangladesh        261.0

[20 rows x 11 columns]

In [35]:
import numpy as np
df['A+ in DS'] = np.where(df['Data Structure Marks'] >= 90,'A+','A')
df

   StudentID          FullName  ...  Total Marks  A+ in DS
0     PH1001       Alif Rahman  ...        258.0         A
1     PH1002     Fatima Akhter  ...          NaN        A+
2     PH1003     Imran Hossain  ...        261.0         A
3     PH1004  Jannatul Ferdous  ...        238.0         A
4     PH1005       Kamal Uddin  ...          NaN         A
5     PH1006       Laila Begum  ...        228.0         A
6     PH1007    Mahmudul Hasan  ...          NaN         A
7     PH1008       Nadia Islam  ...        247.0         A
8     PH1009        Omar Faruq  ...        220.0         A
9     PH1010      Priya Sharma  ...        266.0         A
10    PH1011      Rahim Sheikh  ...          NaN         A
11    PH1012   Sadia Chowdhury  ...        257.0         A
12    PH1013      Tanvir Ahmed  ...        229.0         A
13    PH1014        Urmi Akter  ...          NaN         A
14    PH1015      Wahiduzzaman  ...        256.0         A
15    PH1016      Ziaur Rahman  ...          NaN        A+
16    PH1017       Afsana Mimi  ...        273.0        A+
17    PH1018       Babul Ahmed  ...        261.0         A
18    PH1019      Faria Rahman  ...          NaN         A
19    PH1020        Nasir Khan  ...        261.0         A

[20 rows x 12 columns]

In [36]:
df['Passed in Python'] = df['Python Marks'] >70

df

   StudentID          FullName  ...  A+ in DS  Passed in Python
0     PH1001       Alif Rahman  ...         A              True
1     PH1002     Fatima Akhter  ...        A+             False
2     PH1003     Imran Hossain  ...         A              True
3     PH1004  Jannatul Ferdous  ...         A              True
4     PH1005       Kamal Uddin  ...         A              True
5     PH1006       Laila Begum  ...         A              True
6     PH1007    Mahmudul Hasan  ...         A             False
7     PH1008       Nadia Islam  ...         A              True
8     PH1009        Omar Faruq  ...         A              True
9     PH1010      Priya Sharma  ...         A              True
10    PH1011      Rahim Sheikh  ...         A              True
11    PH1012   Sadia Chowdhury  ...         A              True
12    PH1013      Tanvir Ahmed  ...         A              True
13    PH1014        Urmi Akter  ...         A             False
14    PH1015      Wahiduzzaman  ...         A              True
15    PH1016      Ziaur Rahman  ...        A+             False
16    PH1017       Afsana Mimi  ...        A+              True
17    PH1018       Babul Ahmed  ...         A              True
18    PH1019      Faria Rahman  ...         A             False
19    PH1020        Nasir Khan  ...         A              True

[20 rows x 13 columns]

In [38]:
df['First Name'] = df['FullName'].str.split(' ').str[0]
df

   StudentID          FullName  ...  Passed in Python    First Name
0     PH1001       Alif Rahman  ...              True          Alif
1     PH1002     Fatima Akhter  ...             False        Fatima
2     PH1003     Imran Hossain  ...              True         Imran
3     PH1004  Jannatul Ferdous  ...              True      Jannatul
4     PH1005       Kamal Uddin  ...              True         Kamal
5     PH1006       Laila Begum  ...              True         Laila
6     PH1007    Mahmudul Hasan  ...             False      Mahmudul
7     PH1008       Nadia Islam  ...              True         Nadia
8     PH1009        Omar Faruq  ...              True          Omar
9     PH1010      Priya Sharma  ...              True         Priya
10    PH1011      Rahim Sheikh  ...              True         Rahim
11    PH1012   Sadia Chowdhury  ...              True         Sadia
12    PH1013      Tanvir Ahmed  ...              True        Tanvir
13    PH1014        Urmi Akter  ...             False          Urmi
14    PH1015      Wahiduzzaman  ...              True  Wahiduzzaman
15    PH1016      Ziaur Rahman  ...             False         Ziaur
16    PH1017       Afsana Mimi  ...              True        Afsana
17    PH1018       Babul Ahmed  ...              True         Babul
18    PH1019      Faria Rahman  ...             False         Faria
19    PH1020        Nasir Khan  ...              True         Nasir

[20 rows x 14 columns]

In [39]:
df1 = pd.read_csv('student_data.csv')
df1

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
13    PH1014        Urmi Akter  ...   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
18    PH1019      Faria Rahman  ...   Mr. David  Chattogram
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[20 rows x 9 columns]

In [41]:
#to save the new dataframe

df.to_csv('my_data.csv')

## checking Duplicates and Null values in DF

In [55]:
import pandas as pd 
data = {
    "name": [
        "Alice", "Bob", "Charlie", "David", "Eva",
        "Alice", "Frank", "Grace", "Bob", "Helen","David"
    ],
    
    "city": [
        "New York", "London", "Paris", "Berlin", "Sydney",
        "New York", "Toronto", "Dubai","Paris", "London", "Singapore"
    ],
    
    "department": [
        "IT", "HR", "Finance", "IT", "Marketing",
        "IT", "Sales", "IT", "HR", "IT","HR"
    ],
    
    "salary": [
        70000, 50000, 65000, 72000, 60000,
        70000, 55000, 80000,56000, 50000, 52000
    ]
}
df = pd.DataFrame(data)
print(df)

       name       city department  salary
0     Alice   New York         IT   70000
1       Bob     London         HR   50000
2   Charlie      Paris    Finance   65000
3     David     Berlin         IT   72000
4       Eva     Sydney  Marketing   60000
5     Alice   New York         IT   70000
6     Frank    Toronto      Sales   55000
7     Grace      Dubai         IT   80000
8       Bob      Paris         HR   56000
9     Helen     London         IT   50000
10    David  Singapore         HR   52000

(3, 3)

## unique / duplicate check

In [43]:
#unique works on only series

df['name'].unique()

array(['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace',
       'Helen'], dtype=object)

In [50]:
len(df['salary'].unique())

9

In [52]:
df['salary'].nunique()

9

In [56]:
len(df1['Data Structure Marks'].unique())

13

In [57]:
df1['Data Structure Marks'].nunique()

12

In [58]:
df.nunique()

name          8
city          8
department    5
salary        9
dtype: int64

## Check Null

In [59]:
df1.isnull()

    StudentID  FullName  ...  Instructor  Location
0       False     False  ...       False     False
1       False     False  ...       False     False
2       False     False  ...       False     False
3       False     False  ...       False     False
4       False     False  ...       False     False
5       False     False  ...       False     False
6       False     False  ...       False     False
7       False     False  ...       False     False
8       False     False  ...       False     False
9       False     False  ...       False     False
10      False     False  ...       False     False
11      False     False  ...       False     False
12      False     False  ...       False     False
13      False     False  ...       False     False
14      False     False  ...       False     False
15      False     False  ...       False     False
16      False     False  ...       False     False
17      False     False  ...       False     False
18      False     False  ...       False     False
19      False     False  ...       False     False

[20 rows x 9 columns]

In [60]:
df1['Data Structure Marks'].isnull()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
Name: Data Structure Marks, dtype: bool

In [61]:
df1['Data Structure Marks'].notnull()

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18    False
19     True
Name: Data Structure Marks, dtype: bool

In [62]:
df1['Data Structure Marks'].hasnans
# one column has null values . it will return -> True

True

In [63]:
#for one column check all value -> notnull -> False  
df1['StudentID'].hasnans

False

 ## Handling Duplicate Value

In [68]:
import pandas as pd 

data = {
    "name": [
        "Alice", "Bob", "Charlie",
        "Alice", "Frank", "Bob",
    ],
    
    "city": [
        "New York", "London" , "Sydney",
        "New York", "Toronto", "London"
    ],
    
    "department": [
        "IT", "HR",  "Marketing",
         "Sales",  "Finance","HR"
    ],
    
    "salary": [
        70000, 50000,  72000, 60000,
        70000, 50000, 
    ]
}
df = pd.DataFrame(data)
df

      name      city department  salary
0    Alice  New York         IT   70000
1      Bob    London         HR   50000
2  Charlie    Sydney  Marketing   72000
3    Alice  New York      Sales   60000
4    Frank   Toronto    Finance   70000
5      Bob    London         HR   50000

In [71]:
df.duplicated().sum()

np.int64(1)

In [72]:
# deleting duplicates value  -> row basis
# drop_duplicated()

df.drop_duplicates()

      name      city department  salary
0    Alice  New York         IT   70000
1      Bob    London         HR   50000
2  Charlie    Sydney  Marketing   72000
3    Alice  New York      Sales   60000
4    Frank   Toronto    Finance   70000

In [73]:
df

      name      city department  salary
0    Alice  New York         IT   70000
1      Bob    London         HR   50000
2  Charlie    Sydney  Marketing   72000
3    Alice  New York      Sales   60000
4    Frank   Toronto    Finance   70000
5      Bob    London         HR   50000

In [74]:
# permanenly delete
df.drop_duplicates(inplace=True)

In [75]:
df

      name      city department  salary
0    Alice  New York         IT   70000
1      Bob    London         HR   50000
2  Charlie    Sydney  Marketing   72000
3    Alice  New York      Sales   60000
4    Frank   Toronto    Finance   70000

In [79]:
# delete duplicate -> column basis
df.drop_duplicates(subset=['name'],inplace=True)

In [80]:
df

      name      city department  salary
0    Alice  New York         IT   70000
1      Bob    London         HR   50000
2  Charlie    Sydney  Marketing   72000
4    Frank   Toronto    Finance   70000

## Handling Null Values

In [134]:
# dropna()
import pandas as pd 
df = pd.read_csv('student_data.csv')
df

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
13    PH1014        Urmi Akter  ...   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
18    PH1019      Faria Rahman  ...   Mr. David  Chattogram
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka
20       NaN               NaN  ...         NaN         NaN

[21 rows x 9 columns]

In [135]:
df.dropna()

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[13 rows x 9 columns]

In [136]:
# dropna(how = 'all') -> in row  if all values are null, then it works, otherwise not
 
df.dropna(how = 'all',inplace = True)
df

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
13    PH1014        Urmi Akter  ...   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
18    PH1019      Faria Rahman  ...   Mr. David  Chattogram
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[20 rows x 9 columns]

In [87]:
# deleting by subset like -> column 
df.dropna(subset=['Python Marks'])

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[15 rows x 9 columns]

In [137]:
# deleting by subset like -> column 
df.dropna(subset=['Data Structure Marks'])

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[16 rows x 9 columns]

In [89]:
# deleting by subset like -> column 
df.dropna(subset=['Algorithm Marks'])

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[16 rows x 9 columns]

In [90]:
df

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
13    PH1014        Urmi Akter  ...   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
18    PH1019      Faria Rahman  ...   Mr. David  Chattogram
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[20 rows x 9 columns]

In [93]:
df.dropna(subset=['Algorithm Marks','Data Structure Marks','Python Marks'])

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[13 rows x 9 columns]

In [95]:
# df.fillna() -> assinging value into null place 
df.fillna(0)

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
13    PH1014        Urmi Akter  ...   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
18    PH1019      Faria Rahman  ...   Mr. David  Chattogram
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[20 rows x 9 columns]

In [4]:
import pandas as pd 
df = pd.read_csv('student_data.csv')
df

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
13    PH1014        Urmi Akter  ...   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
18    PH1019      Faria Rahman  ...   Mr. David  Chattogram
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka
20       NaN               NaN  ...         NaN         NaN

[21 rows x 9 columns]

In [5]:
# assigning by column wise with fillna()
df['FullName'].fillna('unkonwn')

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
20             unkonwn
Name: FullName, dtype: object

In [6]:
# assigning by column wise with fillna()
df['Python Marks'].fillna(df['Python Marks'].mean(),inplace = True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_30760\3174612218.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Python Marks'].fillna(df['Python Marks'].mean(),inplace = True)

In [7]:
df

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
4     PH1005       Kamal Uddin  ...   Mr. Karim  Chattogram
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
10    PH1011      Rahim Sheikh  ...   Mr. Karim      Khulna
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
13    PH1014        Urmi Akter  ...   Ms. Salma    Rajshahi
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
18    PH1019      Faria Rahman  ...   Mr. David  Chattogram
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka
20       NaN               NaN  ...         NaN         NaN

[21 rows x 9 columns]

## Statistical Functions

In [8]:
df.dropna()

   StudentID          FullName  ...  Instructor    Location
0     PH1001       Alif Rahman  ...   Mr. Karim       Dhaka
1     PH1002     Fatima Akhter  ...   Ms. Salma  Chattogram
2     PH1003     Imran Hossain  ...   Mr. Karim       Dhaka
3     PH1004  Jannatul Ferdous  ...   Ms. Salma      Sylhet
5     PH1006       Laila Begum  ...   Ms. Salma    Rajshahi
6     PH1007    Mahmudul Hasan  ...   Mr. Karim       Dhaka
7     PH1008       Nadia Islam  ...   Ms. Salma  Chattogram
8     PH1009        Omar Faruq  ...   Mr. David       Dhaka
9     PH1010      Priya Sharma  ...   Ms. Salma      Sylhet
11    PH1012   Sadia Chowdhury  ...   Ms. Salma  Chattogram
12    PH1013      Tanvir Ahmed  ...   Mr. David       Dhaka
14    PH1015      Wahiduzzaman  ...   Mr. Karim       Dhaka
15    PH1016      Ziaur Rahman  ...   Ms. Salma  Chattogram
16    PH1017       Afsana Mimi  ...   Mr. Karim       Dhaka
17    PH1018       Babul Ahmed  ...   Ms. Salma      Sylhet
19    PH1020        Nasir Khan  ...   Ms. Salma       Dhaka

[16 rows x 9 columns]

In [9]:
# for sum 
df['Data Structure Marks'].sum()

np.float64(1344.0)

In [10]:
# maximum and minimum
print(df['Data Structure Marks'].max())

print(df['Data Structure Marks'].min())

94.0
72.0

In [11]:
# mean -> average
print(df['Data Structure Marks'].mean())

84.0

In [12]:
# median -> middle 
df['Data Structure Marks'].median()

85.5

In [13]:
# mode -> highest frequency number 
df['Data Structure Marks'].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Data Structure Marks, dtype: float64

In [14]:
# standard deviation -> std
df['Data Structure Marks'].std()

6.501281924871945

In [15]:
# correelation Matrix 
df[['Data Structure Marks','Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.776845
Python Marks                      0.776845      1.000000

In [16]:
# correelation Matrix 
df[['Data Structure Marks','Algorithm Marks']].corr()

                      Data Structure Marks  Algorithm Marks
Data Structure Marks                   1.0              1.0
Algorithm Marks                        1.0              1.0

In [17]:
# correelation Matrix 
df[['Python Marks','Algorithm Marks']].corr()

                 Python Marks  Algorithm Marks
Python Marks         1.000000         0.776845
Algorithm Marks      0.776845         1.000000

In [18]:
# sum  in different columns 

df[['Data Structure Marks','Python Marks','Algorithm Marks']].sum()

Data Structure Marks    1344.0
Python Marks            1799.0
Algorithm Marks         1344.0
dtype: float64

In [19]:
# sum  in different rows

df[['Data Structure Marks','Python Marks','Algorithm Marks']].sum(axis=1)

0     258.000000
1     269.666667
2     261.000000
3     238.000000
4      95.000000
5     228.000000
6     245.666667
7     247.000000
8     220.000000
9     266.000000
10     91.000000
11    257.000000
12    229.000000
13     85.666667
14    256.000000
15    273.666667
16    273.000000
17    261.000000
18     85.666667
19    261.000000
20     85.666667
dtype: float64

In [20]:
# mean  in different rows

df[['Data Structure Marks','Python Marks','Algorithm Marks']].mean(axis=1)

0     86.000000
1     89.888889
2     87.000000
3     79.333333
4     95.000000
5     76.000000
6     81.888889
7     82.333333
8     73.333333
9     88.666667
10    91.000000
11    85.666667
12    76.333333
13    85.666667
14    85.333333
15    91.222222
16    91.000000
17    87.000000
18    85.666667
19    87.000000
20    85.666667
dtype: float64

In [21]:
# max and min  in different rows
print(df[['Data Structure Marks','Python Marks','Algorithm Marks']].max(axis=1))
print(df[['Data Structure Marks','Python Marks','Algorithm Marks']].min(axis=1))

0     88.000000
1     92.000000
2     88.000000
3     82.000000
4     95.000000
5     78.000000
6     85.666667
7     85.000000
8     76.000000
9     89.000000
10    91.000000
11    87.000000
12    79.000000
13    85.666667
14    86.000000
15    94.000000
16    93.000000
17    88.000000
18    85.666667
19    89.000000
20    85.666667
dtype: float64
0     85.000000
1     85.666667
2     85.000000
3     78.000000
4     95.000000
5     75.000000
6     80.000000
7     81.000000
8     72.000000
9     88.000000
10    91.000000
11    85.000000
12    75.000000
13    85.666667
14    84.000000
15    85.666667
16    90.000000
17    85.000000
18    85.666667
19    86.000000
20    85.666667
dtype: float64

In [24]:
# total marks 
df['Total Marks'] = df.iloc[::,2:5].sum(axis = 1)
df

   StudentID          FullName  ...    Location  Total Marks
0     PH1001       Alif Rahman  ...       Dhaka   258.000000
1     PH1002     Fatima Akhter  ...  Chattogram   269.666667
2     PH1003     Imran Hossain  ...       Dhaka   261.000000
3     PH1004  Jannatul Ferdous  ...      Sylhet   238.000000
4     PH1005       Kamal Uddin  ...  Chattogram    95.000000
5     PH1006       Laila Begum  ...    Rajshahi   228.000000
6     PH1007    Mahmudul Hasan  ...       Dhaka   245.666667
7     PH1008       Nadia Islam  ...  Chattogram   247.000000
8     PH1009        Omar Faruq  ...       Dhaka   220.000000
9     PH1010      Priya Sharma  ...      Sylhet   266.000000
10    PH1011      Rahim Sheikh  ...      Khulna    91.000000
11    PH1012   Sadia Chowdhury  ...  Chattogram   257.000000
12    PH1013      Tanvir Ahmed  ...       Dhaka   229.000000
13    PH1014        Urmi Akter  ...    Rajshahi    85.666667
14    PH1015      Wahiduzzaman  ...       Dhaka   256.000000
15    PH1016      Ziaur Rahman  ...  Chattogram   273.666667
16    PH1017       Afsana Mimi  ...       Dhaka   273.000000
17    PH1018       Babul Ahmed  ...      Sylhet   261.000000
18    PH1019      Faria Rahman  ...  Chattogram    85.666667
19    PH1020        Nasir Khan  ...       Dhaka   261.000000
20       NaN               NaN  ...         NaN    85.666667

[21 rows x 10 columns]

## applying function in df

In [25]:
df

   StudentID          FullName  ...    Location  Total Marks
0     PH1001       Alif Rahman  ...       Dhaka   258.000000
1     PH1002     Fatima Akhter  ...  Chattogram   269.666667
2     PH1003     Imran Hossain  ...       Dhaka   261.000000
3     PH1004  Jannatul Ferdous  ...      Sylhet   238.000000
4     PH1005       Kamal Uddin  ...  Chattogram    95.000000
5     PH1006       Laila Begum  ...    Rajshahi   228.000000
6     PH1007    Mahmudul Hasan  ...       Dhaka   245.666667
7     PH1008       Nadia Islam  ...  Chattogram   247.000000
8     PH1009        Omar Faruq  ...       Dhaka   220.000000
9     PH1010      Priya Sharma  ...      Sylhet   266.000000
10    PH1011      Rahim Sheikh  ...      Khulna    91.000000
11    PH1012   Sadia Chowdhury  ...  Chattogram   257.000000
12    PH1013      Tanvir Ahmed  ...       Dhaka   229.000000
13    PH1014        Urmi Akter  ...    Rajshahi    85.666667
14    PH1015      Wahiduzzaman  ...       Dhaka   256.000000
15    PH1016      Ziaur Rahman  ...  Chattogram   273.666667
16    PH1017       Afsana Mimi  ...       Dhaka   273.000000
17    PH1018       Babul Ahmed  ...      Sylhet   261.000000
18    PH1019      Faria Rahman  ...  Chattogram    85.666667
19    PH1020        Nasir Khan  ...       Dhaka   261.000000
20       NaN               NaN  ...         NaN    85.666667

[21 rows x 10 columns]

In [26]:
# min max scaling 

minimum = df['Total Marks'].min()
maximum = df['Total Marks'].max()
df['Scaled Marks'] = df['Total Marks'].apply(lambda x : (x-minimum)/ (maximum-minimum))
df

   StudentID          FullName  ...  Total Marks  Scaled Marks
0     PH1001       Alif Rahman  ...   258.000000      0.916667
1     PH1002     Fatima Akhter  ...   269.666667      0.978723
2     PH1003     Imran Hossain  ...   261.000000      0.932624
3     PH1004  Jannatul Ferdous  ...   238.000000      0.810284
4     PH1005       Kamal Uddin  ...    95.000000      0.049645
5     PH1006       Laila Begum  ...   228.000000      0.757092
6     PH1007    Mahmudul Hasan  ...   245.666667      0.851064
7     PH1008       Nadia Islam  ...   247.000000      0.858156
8     PH1009        Omar Faruq  ...   220.000000      0.714539
9     PH1010      Priya Sharma  ...   266.000000      0.959220
10    PH1011      Rahim Sheikh  ...    91.000000      0.028369
11    PH1012   Sadia Chowdhury  ...   257.000000      0.911348
12    PH1013      Tanvir Ahmed  ...   229.000000      0.762411
13    PH1014        Urmi Akter  ...    85.666667      0.000000
14    PH1015      Wahiduzzaman  ...   256.000000      0.906028
15    PH1016      Ziaur Rahman  ...   273.666667      1.000000
16    PH1017       Afsana Mimi  ...   273.000000      0.996454
17    PH1018       Babul Ahmed  ...   261.000000      0.932624
18    PH1019      Faria Rahman  ...    85.666667      0.000000
19    PH1020        Nasir Khan  ...   261.000000      0.932624
20       NaN               NaN  ...    85.666667      0.000000

[21 rows x 11 columns]

In [28]:
# custom built function
def grading_system(marks):
    if marks >= 260: 
        return 'A+'
    elif marks >= 250: 
        return 'A' 
    else: 
        return 'A-'


df['Grade'] = df['Total Marks'].apply( grading_system) 
df

   StudentID          FullName  ...  Scaled Marks  Grade
0     PH1001       Alif Rahman  ...      0.916667      A
1     PH1002     Fatima Akhter  ...      0.978723     A+
2     PH1003     Imran Hossain  ...      0.932624     A+
3     PH1004  Jannatul Ferdous  ...      0.810284     A-
4     PH1005       Kamal Uddin  ...      0.049645     A-
5     PH1006       Laila Begum  ...      0.757092     A-
6     PH1007    Mahmudul Hasan  ...      0.851064     A-
7     PH1008       Nadia Islam  ...      0.858156     A-
8     PH1009        Omar Faruq  ...      0.714539     A-
9     PH1010      Priya Sharma  ...      0.959220     A+
10    PH1011      Rahim Sheikh  ...      0.028369     A-
11    PH1012   Sadia Chowdhury  ...      0.911348      A
12    PH1013      Tanvir Ahmed  ...      0.762411     A-
13    PH1014        Urmi Akter  ...      0.000000     A-
14    PH1015      Wahiduzzaman  ...      0.906028      A
15    PH1016      Ziaur Rahman  ...      1.000000     A+
16    PH1017       Afsana Mimi  ...      0.996454     A+
17    PH1018       Babul Ahmed  ...      0.932624     A+
18    PH1019      Faria Rahman  ...      0.000000     A-
19    PH1020        Nasir Khan  ...      0.932624     A+
20       NaN               NaN  ...      0.000000     A-

[21 rows x 12 columns]

In [32]:
def marking_system(df): 
    a = df['Data Structure Marks'] * 0.2 #20%
    b = df['Algorithm Marks'] * 0.15 #15%
    c = df['Python Marks'] * 0.15 #15%

    return a+b+c 

df['Exceptional Marks'] = df.apply(marking_system,axis = 1)  
df

   StudentID          FullName  ...  Grade  Exceptional Marks
0     PH1001       Alif Rahman  ...      A              42.95
1     PH1002     Fatima Akhter  ...     A+              45.05
2     PH1003     Imran Hossain  ...     A+              43.55
3     PH1004  Jannatul Ferdous  ...     A-              39.60
4     PH1005       Kamal Uddin  ...     A-                NaN
5     PH1006       Laila Begum  ...     A-              37.95
6     PH1007    Mahmudul Hasan  ...     A-              40.85
7     PH1008       Nadia Islam  ...     A-              41.10
8     PH1009        Omar Faruq  ...     A-              36.60
9     PH1010      Priya Sharma  ...     A+              44.35
10    PH1011      Rahim Sheikh  ...     A-                NaN
11    PH1012   Sadia Chowdhury  ...      A              42.80
12    PH1013      Tanvir Ahmed  ...     A-              38.10
13    PH1014        Urmi Akter  ...     A-                NaN
14    PH1015      Wahiduzzaman  ...      A              42.70
15    PH1016      Ziaur Rahman  ...     A+              45.75
16    PH1017       Afsana Mimi  ...     A+              45.45
17    PH1018       Babul Ahmed  ...     A+              43.55
18    PH1019      Faria Rahman  ...     A-                NaN
19    PH1020        Nasir Khan  ...     A+              43.45
20       NaN               NaN  ...     A-                NaN

[21 rows x 13 columns]

## DateTime and Time Delta

In [33]:
df = pd.read_csv('student_completed_data.csv')
df

   StudentID          FullName  ...    Location Total Marks
0     PH0001       Alif Rahman  ...      Khulna         300
1     PH0002     Fatima Akhter  ...       Dhaka         271
2     PH0003     Imran Hossain  ...       Dhaka         269
3     PH0004  Jannatul Ferdous  ...      Khulna         270
4     PH0005       Kamal Uddin  ...      Sylhet         254
5     PH0006       Laila Begum  ...      Khulna         272
6     PH0007    Mahmudul Hasan  ...  Chattogram         249
7     PH0008       Nadia Islam  ...      Khulna         246
8     PH0009        Omar Faruq  ...       Dhaka         291
9     PH0010      Priya Sharma  ...       Dhaka         286
10    PH0011      Rahim Sheikh  ...      Sylhet         283
11    PH0012   Sadia Chowdhury  ...      Sylhet         266
12    PH0013      Tanvir Ahmed  ...       Dhaka         248
13    PH0014        Urmi Akter  ...      Sylhet         285
14    PH0015      Wahiduzzaman  ...    Rajshahi         291
15    PH0016      Ziaur Rahman  ...    Rajshahi         234
16    PH0017       Afsana Mimi  ...      Khulna         236
17    PH0018       Babul Ahmed  ...       Dhaka         278
18    PH0019      Faria Rahman  ...      Sylhet         277
19    PH0020       Tariq Hasan  ...      Khulna         253

[20 rows x 8 columns]

In [34]:
df['EnrollmentDate']

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: object

In [35]:
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'])
df['EnrollmentDate']

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[ns]

In [36]:
df['Enrollment Year'] = df['EnrollmentDate'].dt.year

In [37]:
df

   StudentID          FullName  ... Total Marks Enrollment Year
0     PH0001       Alif Rahman  ...         300            2024
1     PH0002     Fatima Akhter  ...         271            2024
2     PH0003     Imran Hossain  ...         269            2024
3     PH0004  Jannatul Ferdous  ...         270            2024
4     PH0005       Kamal Uddin  ...         254            2024
5     PH0006       Laila Begum  ...         272            2024
6     PH0007    Mahmudul Hasan  ...         249            2024
7     PH0008       Nadia Islam  ...         246            2024
8     PH0009        Omar Faruq  ...         291            2024
9     PH0010      Priya Sharma  ...         286            2024
10    PH0011      Rahim Sheikh  ...         283            2024
11    PH0012   Sadia Chowdhury  ...         266            2024
12    PH0013      Tanvir Ahmed  ...         248            2024
13    PH0014        Urmi Akter  ...         285            2024
14    PH0015      Wahiduzzaman  ...         291            2024
15    PH0016      Ziaur Rahman  ...         234            2024
16    PH0017       Afsana Mimi  ...         236            2024
17    PH0018       Babul Ahmed  ...         278            2024
18    PH0019      Faria Rahman  ...         277            2024
19    PH0020       Tariq Hasan  ...         253            2024

[20 rows x 9 columns]

In [38]:
df['Enrollment Date'] = df['EnrollmentDate'].dt.day

In [39]:
df

   StudentID          FullName  ... Enrollment Year Enrollment Date
0     PH0001       Alif Rahman  ...            2024               1
1     PH0002     Fatima Akhter  ...            2024              11
2     PH0003     Imran Hossain  ...            2024               8
3     PH0004  Jannatul Ferdous  ...            2024               5
4     PH0005       Kamal Uddin  ...            2024               1
5     PH0006       Laila Begum  ...            2024               7
6     PH0007    Mahmudul Hasan  ...            2024               7
7     PH0008       Nadia Islam  ...            2024              22
8     PH0009        Omar Faruq  ...            2024              12
9     PH0010      Priya Sharma  ...            2024              19
10    PH0011      Rahim Sheikh  ...            2024              14
11    PH0012   Sadia Chowdhury  ...            2024               4
12    PH0013      Tanvir Ahmed  ...            2024               7
13    PH0014        Urmi Akter  ...            2024               4
14    PH0015      Wahiduzzaman  ...            2024              22
15    PH0016      Ziaur Rahman  ...            2024              23
16    PH0017       Afsana Mimi  ...            2024              18
17    PH0018       Babul Ahmed  ...            2024              23
18    PH0019      Faria Rahman  ...            2024              19
19    PH0020       Tariq Hasan  ...            2024              21

[20 rows x 10 columns]

In [42]:
df['FinishedDate'] = pd.to_datetime(df['FinishedDate'])

In [43]:
df['Total Time taken to Finish'] = df['FinishedDate'] - df['EnrollmentDate']
df

   StudentID          FullName  ... Finished Date Total Time taken to Finish
0     PH0001       Alif Rahman  ...    2024-12-23                   113 days
1     PH0002     Fatima Akhter  ...    2024-11-07                    88 days
2     PH0003     Imran Hossain  ...    2024-08-08                    92 days
3     PH0004  Jannatul Ferdous  ...    2024-09-23                    80 days
4     PH0005       Kamal Uddin  ...    2024-04-17                    76 days
5     PH0006       Laila Begum  ...    2024-12-31                   115 days
6     PH0007    Mahmudul Hasan  ...    2024-07-20                    43 days
7     PH0008       Nadia Islam  ...    2024-05-01                    40 days
8     PH0009        Omar Faruq  ...    2024-06-08                   117 days
9     PH0010      Priya Sharma  ...    2024-08-19                    61 days
10    PH0011      Rahim Sheikh  ...    2024-06-11                    89 days
11    PH0012   Sadia Chowdhury  ...    2024-10-25                    82 days
12    PH0013      Tanvir Ahmed  ...    2024-08-03                    57 days
13    PH0014        Urmi Akter  ...    2024-03-23                    79 days
14    PH0015      Wahiduzzaman  ...    2024-05-16                    84 days
15    PH0016      Ziaur Rahman  ...    2024-06-21                    90 days
16    PH0017       Afsana Mimi  ...    2024-03-16                    58 days
17    PH0018       Babul Ahmed  ...    2024-09-20                    89 days
18    PH0019      Faria Rahman  ...    2024-08-17                   120 days
19    PH0020       Tariq Hasan  ...    2024-10-11                    82 days

[20 rows x 12 columns]

## GroupBy

In [1]:
import pandas as pd 

df = pd.read_csv('student_completed_data.csv') 
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [2]:
import numpy as np 
df.loc[df['FullName'] == 'Afsana Mimi','Total Marks'] = np.nan
df.loc[df['FullName'] == 'Sadia Chowdhury','Total Marks'] = np.nan
df.loc[df['FullName'] == 'Alif Rahman','Total Marks'] = np.nan

In [3]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,NaN
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.0
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.0
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.0
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.0
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.0
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.0
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,NaN
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.0
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.0
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.0

In [4]:
instructor_group = df.groupby('Instructor')
instructor_group

In [6]:
for instructor , df_ins in instructor_group:
    print(instructor)
    display(df_ins)

Mr. David

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0

Mr. Karim

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.0
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.0
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.0
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.0
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,NaN
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.0
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.0

Ms. Salma

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,NaN
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.0
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.0
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.0

In [7]:
instructor_group.min()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks
Instructor,,,,,,,
Mr. David,PH0005,Afsana Mimi,Completed,2024-01-04,2024-03-16,Chattogram,248.0
Mr. Karim,PH0002,Faria Rahman,Completed,2024-02-12,2024-06-08,Dhaka,253.0
Ms. Salma,PH0001,Alif Rahman,Completed,2024-03-22,2024-05-01,Dhaka,234.0

In [8]:
instructor_group.describe()

           Total Marks                                                       \
                 count        mean        std    min     25%    50%     75%
Instructor
Mr. David          8.0  270.375000  17.606310  248.0  252.75  275.0  285.25
Mr. Karim          6.0  274.166667  12.998718  253.0  270.25  274.0  281.50
Ms. Salma          3.0  249.666667  17.785762  234.0  240.00  246.0  257.50


              max
Instructor
Mr. David   291.0
Mr. Karim   291.0
Ms. Salma   269.0

In [10]:
mean_marks = instructor_group['Total Marks'].mean()
mean_marks

Instructor
Mr. David    270.375000
Mr. Karim    274.166667
Ms. Salma    249.666667
Name: Total Marks, dtype: float64

In [12]:
df['Total Marks'] = df['Total Marks'].fillna(df['Instructor'].map(mean_marks))
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,249.666667
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.000000
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.000000
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.000000
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.000000
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.000000
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.000000
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.000000
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.000000
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.000000
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.000000
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,274.166667
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.000000
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.000000
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.000000
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.000000
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,270.375000
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.000000
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.000000
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.000000